config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :loans
  resources :credits
  resources :users
  
get 'loans/:id/show_calc', to: 'loans#show_calc'

  root to: 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :credit
  
  before_save do
    pmt = 0
    pmt = self.value * ((((1 + self.tax) ** self.portion) * self.tax) / (((1 + self.tax) ** self.portion) - 1))
    self.total = pmt
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :credit

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: %i[ show edit update destroy ]

  # GET /credits or /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1 or /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits or /credits.json
  def create
    @credit = Credit.new(credit_params)
    @credit.user_id = current_user.id if current_user
    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: "Credit was successfully created." }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1 or /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: "Credit was successfully updated." }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1 or /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: "Credit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def credit_params
      params.require(:credit).permit(:value, :approval, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @loans = Loan.all(current_user)
     @credits = Credit.all(current_user)
  end

  def method_name
    
  end
  
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show
    
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: "Loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:value, :portion, :tax, :user_id, :credit_id, :total)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
   
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:id, :name, :document, :address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper

    def format_currency(total)
        number_to_currency(total, :unit => "R$ ", :separator => ",", :delimiter => ".")
            #"R$" + sprintf("%5.2f", total)       
    end
    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credits/_form.html.erb
<%=render 'layouts/partials/menu' %>

<%= form_with(model: credit, local: true) do |form| %>
  <% if credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
        <% credit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form', credit: @credit %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credits</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Approval</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.value %></td>
        <td><%= credit.approval %></td>
        <td><%= credit.user_id %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form', credit: @credit %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @credit.value %>
</p>

<p>
  <strong>Approval:</strong>
  <%= @credit.approval %>
</p>

<p>
  <strong>User:</strong>
  <%= @credit.user_id %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%=render 'layouts/partials/menu' %>

<h1>Credits</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Value</th>
            <th>Approval</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @credits.each do |credit| %>
            <tr>
                <td>
                    <%= credit.id %>
                </td>
                <td>
                    <%= format_currency(credit.value) %>
                </td>
                <td>
                    <%= credit.approval %>
                </td>
                
                
            </tr>
            <% end %>
    </tbody>
</table>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Portion</th>
      <th>Tax</th>
      <th>User</th>
      <th>Credit</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= format_currency(loan.value) %></td>
        <td><%= loan.portion %>X</td>
        <td><%= loan.tax %></td>
        <td><%= loan.user_id %></td>
        <td><%= loan.credit_id %></td>
        <td><%= format_currency(loan.total) %></td>
        <td><%= link_to 'Visualizar Parcelas', loan %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_menu.html.erb
<%= link_to "Home" , root_path %> |

<%= link_to "Solicitar Crédito" , new_credit_path %> |

<%= link_to 'Solicitar Empréstimo' , new_loan_path %> |

<%= link_to('Logout', destroy_user_session_path, method: :delete) %>

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :portion %>
    <%= form.number_field :portion %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :credit_id %>
    <%= form.text_field :credit_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Portion</th>
      <th>Tax</th>
      <th>User</th>
      <th>Credit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= format_currency(loan.value) %></td>
        <td><%= loan.portion %></td>
        <td><%= loan.tax %></td>
        <td><%= loan.user_id %></td>
        <td><%= loan.credit_id %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= format_currency(@loan.value) %>
</p>

<p>
  <strong>Portion:</strong>
  <%= @loan.portion %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @loan.tax %>
</p>

<p>
  <strong>User:</strong>
  <%= @loan.user_id %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @loan.credit_id %>
</p>

<p>
  <strong>Total:</strong>
  <%= format_currency(@loan.total) %>
</p>
<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.text_field :document %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Document</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.document %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @user.document %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>